services:
  - type: web
    name: fake-twitter-account-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_app.py
    envVars:
      - key: TWITTER_BEARER_TOKEN
        sync: false
